-- 建表语句
CREATE TABLE `ivy_menu` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`is_enable` TINYINT(1)  DEFAULT NULL  COMMENT '是否启用[0:未启用,1:启用]',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `ivy_menu` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `ivy_menu` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `ivy_menu` ADD COLUMN is_enable TINYINT(1)  DEFAULT NULL  COMMENT '是否启用[0:未启用,1:启用]';

