-- 建表语句
CREATE TABLE `ivy_statistics` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`type` VARCHAR(32)  DEFAULT NULL  COMMENT '类型',
`remark` VARCHAR(32)  DEFAULT NULL  COMMENT '描述',
`total_count` INTEGER(11)  DEFAULT NULL  COMMENT '总次数',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `ivy_statistics` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `ivy_statistics` ADD COLUMN type VARCHAR(32)  DEFAULT NULL  COMMENT '类型';
ALTER TABLE `ivy_statistics` ADD COLUMN remark VARCHAR(32)  DEFAULT NULL  COMMENT '描述';
ALTER TABLE `ivy_statistics` ADD COLUMN total_count INTEGER(11)  DEFAULT NULL  COMMENT '总次数';

