-- 建表语句
CREATE TABLE `ivy_user` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`username` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`password` VARCHAR(32)  DEFAULT NULL  COMMENT '密码',
`email` VARCHAR(32)  DEFAULT NULL  COMMENT '邮箱',
`is_enable` TINYINT(1)  DEFAULT NULL  COMMENT '是否启用[0:未启用,1:启用]',
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `ivy_user` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `ivy_user` ADD COLUMN username VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `ivy_user` ADD COLUMN password VARCHAR(32)  DEFAULT NULL  COMMENT '密码';
ALTER TABLE `ivy_user` ADD COLUMN email VARCHAR(32)  DEFAULT NULL  COMMENT '邮箱';
ALTER TABLE `ivy_user` ADD COLUMN is_enable TINYINT(1)  DEFAULT NULL  COMMENT '是否启用[0:未启用,1:启用]';

