-- 建表语句
CREATE TABLE `ppsg_checkpoint` (
`id` BIGINT(20)  NOT NULL AUTO_INCREMENT ,
`name` VARCHAR(32)  DEFAULT NULL  COMMENT '名称',
`forces` INTEGER(11)  DEFAULT NULL  COMMENT '武力',
`intellect` INTEGER(11)  DEFAULT NULL  COMMENT '智力',
`troops` INTEGER(11)  DEFAULT NULL  COMMENT '兵力',
`c30_1` INTEGER(11)  DEFAULT NULL ,
`c30_2` INTEGER(11)  DEFAULT NULL ,
`c30_3` INTEGER(11)  DEFAULT NULL ,
`c30_4` INTEGER(11)  DEFAULT NULL ,
`c30_5` INTEGER(11)  DEFAULT NULL ,
`c30_6` INTEGER(11)  DEFAULT NULL ,
`c30_7` INTEGER(11)  DEFAULT NULL ,
`c30_8` INTEGER(11)  DEFAULT NULL ,
`c30_9` INTEGER(11)  DEFAULT NULL ,
`c30_10` INTEGER(11)  DEFAULT NULL ,
`c30_11` INTEGER(11)  DEFAULT NULL ,
`c30_12` INTEGER(11)  DEFAULT NULL ,
`c29_1` INTEGER(11)  DEFAULT NULL ,
`c29_2` INTEGER(11)  DEFAULT NULL ,
`c29_3` INTEGER(11)  DEFAULT NULL ,
`c29_4` INTEGER(11)  DEFAULT NULL ,
`c29_5` INTEGER(11)  DEFAULT NULL ,
`c29_6` INTEGER(11)  DEFAULT NULL ,
`c29_7` INTEGER(11)  DEFAULT NULL ,
`c29_8` INTEGER(11)  DEFAULT NULL ,
`c29_9` INTEGER(11)  DEFAULT NULL ,
`c29_10` INTEGER(11)  DEFAULT NULL ,
`c29_11` INTEGER(11)  DEFAULT NULL ,
`c29_12` INTEGER(11)  DEFAULT NULL ,
`c28_1` INTEGER(11)  DEFAULT NULL ,
`c28_2` INTEGER(11)  DEFAULT NULL ,
`c28_3` INTEGER(11)  DEFAULT NULL ,
`c28_4` INTEGER(11)  DEFAULT NULL ,
`c28_5` INTEGER(11)  DEFAULT NULL ,
`c28_6` INTEGER(11)  DEFAULT NULL ,
`c28_7` INTEGER(11)  DEFAULT NULL ,
`c28_8` INTEGER(11)  DEFAULT NULL ,
`c28_9` INTEGER(11)  DEFAULT NULL ,
`c28_10` INTEGER(11)  DEFAULT NULL ,
`c28_11` INTEGER(11)  DEFAULT NULL ,
`c28_12` INTEGER(11)  DEFAULT NULL ,
`c27_1` INTEGER(11)  DEFAULT NULL ,
`c27_2` INTEGER(11)  DEFAULT NULL ,
`c27_3` INTEGER(11)  DEFAULT NULL ,
`c27_4` INTEGER(11)  DEFAULT NULL ,
`c27_5` INTEGER(11)  DEFAULT NULL ,
`c27_6` INTEGER(11)  DEFAULT NULL ,
`c27_7` INTEGER(11)  DEFAULT NULL ,
`c27_8` INTEGER(11)  DEFAULT NULL ,
`c27_9` INTEGER(11)  DEFAULT NULL ,
`c27_10` INTEGER(11)  DEFAULT NULL ,
`c27_11` INTEGER(11)  DEFAULT NULL ,
`c27_12` INTEGER(11)  DEFAULT NULL ,
`c26_1` INTEGER(11)  DEFAULT NULL ,
`c26_2` INTEGER(11)  DEFAULT NULL ,
`c26_3` INTEGER(11)  DEFAULT NULL ,
`c26_4` INTEGER(11)  DEFAULT NULL ,
`c26_5` INTEGER(11)  DEFAULT NULL ,
`c26_6` INTEGER(11)  DEFAULT NULL ,
`c26_7` INTEGER(11)  DEFAULT NULL ,
`c26_8` INTEGER(11)  DEFAULT NULL ,
`c26_9` INTEGER(11)  DEFAULT NULL ,
`c26_10` INTEGER(11)  DEFAULT NULL ,
`c26_11` INTEGER(11)  DEFAULT NULL ,
`c26_12` INTEGER(11)  DEFAULT NULL ,
`c25_1` INTEGER(11)  DEFAULT NULL ,
`c25_2` INTEGER(11)  DEFAULT NULL ,
`c25_3` INTEGER(11)  DEFAULT NULL ,
`c25_4` INTEGER(11)  DEFAULT NULL ,
`c25_5` INTEGER(11)  DEFAULT NULL ,
`c25_6` INTEGER(11)  DEFAULT NULL ,
`c25_7` INTEGER(11)  DEFAULT NULL ,
`c25_8` INTEGER(11)  DEFAULT NULL ,
`c25_9` INTEGER(11)  DEFAULT NULL ,
`c25_10` INTEGER(11)  DEFAULT NULL ,
`c25_11` INTEGER(11)  DEFAULT NULL ,
`c25_12` INTEGER(11)  DEFAULT NULL ,
`c24_1` INTEGER(11)  DEFAULT NULL ,
`c24_2` INTEGER(11)  DEFAULT NULL ,
`c24_3` INTEGER(11)  DEFAULT NULL ,
`c24_4` INTEGER(11)  DEFAULT NULL ,
`c24_5` INTEGER(11)  DEFAULT NULL ,
`c24_6` INTEGER(11)  DEFAULT NULL ,
`c24_7` INTEGER(11)  DEFAULT NULL ,
`c24_8` INTEGER(11)  DEFAULT NULL ,
`c24_9` INTEGER(11)  DEFAULT NULL ,
`c24_10` INTEGER(11)  DEFAULT NULL ,
`c24_11` INTEGER(11)  DEFAULT NULL ,
`c24_12` INTEGER(11)  DEFAULT NULL ,
`c23_1` INTEGER(11)  DEFAULT NULL ,
`c23_2` INTEGER(11)  DEFAULT NULL ,
`c23_3` INTEGER(11)  DEFAULT NULL ,
`c23_4` INTEGER(11)  DEFAULT NULL ,
`c23_5` INTEGER(11)  DEFAULT NULL ,
`c23_6` INTEGER(11)  DEFAULT NULL ,
`c23_7` INTEGER(11)  DEFAULT NULL ,
`c23_8` INTEGER(11)  DEFAULT NULL ,
`c23_9` INTEGER(11)  DEFAULT NULL ,
`c23_10` INTEGER(11)  DEFAULT NULL ,
`c23_11` INTEGER(11)  DEFAULT NULL ,
`c23_12` INTEGER(11)  DEFAULT NULL ,
`c22_1` INTEGER(11)  DEFAULT NULL ,
`c22_2` INTEGER(11)  DEFAULT NULL ,
`c22_3` INTEGER(11)  DEFAULT NULL ,
`c22_4` INTEGER(11)  DEFAULT NULL ,
`c22_5` INTEGER(11)  DEFAULT NULL ,
`c22_6` INTEGER(11)  DEFAULT NULL ,
`c22_7` INTEGER(11)  DEFAULT NULL ,
`c22_8` INTEGER(11)  DEFAULT NULL ,
`c22_9` INTEGER(11)  DEFAULT NULL ,
`c22_10` INTEGER(11)  DEFAULT NULL ,
`c22_11` INTEGER(11)  DEFAULT NULL ,
`c22_12` INTEGER(11)  DEFAULT NULL ,
`c21_1` INTEGER(11)  DEFAULT NULL ,
`c21_2` INTEGER(11)  DEFAULT NULL ,
`c21_3` INTEGER(11)  DEFAULT NULL ,
`c21_4` INTEGER(11)  DEFAULT NULL ,
`c21_5` INTEGER(11)  DEFAULT NULL ,
`c21_6` INTEGER(11)  DEFAULT NULL ,
`c21_7` INTEGER(11)  DEFAULT NULL ,
`c21_8` INTEGER(11)  DEFAULT NULL ,
`c21_9` INTEGER(11)  DEFAULT NULL ,
`c21_10` INTEGER(11)  DEFAULT NULL ,
`c21_11` INTEGER(11)  DEFAULT NULL ,
`c21_12` INTEGER(11)  DEFAULT NULL ,
`c20_1` INTEGER(11)  DEFAULT NULL ,
`c20_2` INTEGER(11)  DEFAULT NULL ,
`c20_3` INTEGER(11)  DEFAULT NULL ,
`c20_4` INTEGER(11)  DEFAULT NULL ,
`c20_5` INTEGER(11)  DEFAULT NULL ,
`c20_6` INTEGER(11)  DEFAULT NULL ,
`c20_7` INTEGER(11)  DEFAULT NULL ,
`c20_8` INTEGER(11)  DEFAULT NULL ,
`c20_9` INTEGER(11)  DEFAULT NULL ,
`c20_10` INTEGER(11)  DEFAULT NULL ,
`c20_11` INTEGER(11)  DEFAULT NULL ,
`c20_12` INTEGER(11)  DEFAULT NULL ,
`c19_1` INTEGER(11)  DEFAULT NULL ,
`c19_2` INTEGER(11)  DEFAULT NULL ,
`c19_3` INTEGER(11)  DEFAULT NULL ,
`c19_4` INTEGER(11)  DEFAULT NULL ,
`c19_5` INTEGER(11)  DEFAULT NULL ,
`c19_6` INTEGER(11)  DEFAULT NULL ,
`c19_7` INTEGER(11)  DEFAULT NULL ,
`c19_8` INTEGER(11)  DEFAULT NULL ,
`c19_9` INTEGER(11)  DEFAULT NULL ,
`c19_10` INTEGER(11)  DEFAULT NULL ,
`c19_11` INTEGER(11)  DEFAULT NULL ,
`c19_12` INTEGER(11)  DEFAULT NULL ,
`c18_1` INTEGER(11)  DEFAULT NULL ,
`c18_2` INTEGER(11)  DEFAULT NULL ,
`c18_3` INTEGER(11)  DEFAULT NULL ,
`c18_4` INTEGER(11)  DEFAULT NULL ,
`c18_5` INTEGER(11)  DEFAULT NULL ,
`c18_6` INTEGER(11)  DEFAULT NULL ,
`c18_7` INTEGER(11)  DEFAULT NULL ,
`c18_8` INTEGER(11)  DEFAULT NULL ,
`c18_9` INTEGER(11)  DEFAULT NULL ,
`c18_10` INTEGER(11)  DEFAULT NULL ,
`c18_11` INTEGER(11)  DEFAULT NULL ,
`c18_12` INTEGER(11)  DEFAULT NULL ,
`c17_1` INTEGER(11)  DEFAULT NULL ,
`c17_2` INTEGER(11)  DEFAULT NULL ,
`c17_3` INTEGER(11)  DEFAULT NULL ,
`c17_4` INTEGER(11)  DEFAULT NULL ,
`c17_5` INTEGER(11)  DEFAULT NULL ,
`c17_6` INTEGER(11)  DEFAULT NULL ,
`c17_7` INTEGER(11)  DEFAULT NULL ,
`c17_8` INTEGER(11)  DEFAULT NULL ,
`c17_9` INTEGER(11)  DEFAULT NULL ,
`c17_10` INTEGER(11)  DEFAULT NULL ,
`c17_11` INTEGER(11)  DEFAULT NULL ,
`c17_12` INTEGER(11)  DEFAULT NULL ,
`c16_1` INTEGER(11)  DEFAULT NULL ,
`c16_2` INTEGER(11)  DEFAULT NULL ,
`c16_3` INTEGER(11)  DEFAULT NULL ,
`c16_4` INTEGER(11)  DEFAULT NULL ,
`c16_5` INTEGER(11)  DEFAULT NULL ,
`c16_6` INTEGER(11)  DEFAULT NULL ,
`c16_7` INTEGER(11)  DEFAULT NULL ,
`c16_8` INTEGER(11)  DEFAULT NULL ,
`c16_9` INTEGER(11)  DEFAULT NULL ,
`c16_10` INTEGER(11)  DEFAULT NULL ,
`c16_11` INTEGER(11)  DEFAULT NULL ,
`c16_12` INTEGER(11)  DEFAULT NULL ,
`c15_1` INTEGER(11)  DEFAULT NULL ,
`c15_2` INTEGER(11)  DEFAULT NULL ,
`c15_3` INTEGER(11)  DEFAULT NULL ,
`c15_4` INTEGER(11)  DEFAULT NULL ,
`c15_5` INTEGER(11)  DEFAULT NULL ,
`c15_6` INTEGER(11)  DEFAULT NULL ,
`c15_7` INTEGER(11)  DEFAULT NULL ,
`c15_8` INTEGER(11)  DEFAULT NULL ,
`c15_9` INTEGER(11)  DEFAULT NULL ,
`c15_10` INTEGER(11)  DEFAULT NULL ,
`c15_11` INTEGER(11)  DEFAULT NULL ,
`c15_12` INTEGER(11)  DEFAULT NULL ,
`c14_1` INTEGER(11)  DEFAULT NULL ,
`c14_2` INTEGER(11)  DEFAULT NULL ,
`c14_3` INTEGER(11)  DEFAULT NULL ,
`c14_4` INTEGER(11)  DEFAULT NULL ,
`c14_5` INTEGER(11)  DEFAULT NULL ,
`c14_6` INTEGER(11)  DEFAULT NULL ,
`c14_7` INTEGER(11)  DEFAULT NULL ,
`c14_8` INTEGER(11)  DEFAULT NULL ,
`c14_9` INTEGER(11)  DEFAULT NULL ,
`c14_10` INTEGER(11)  DEFAULT NULL ,
`c14_11` INTEGER(11)  DEFAULT NULL ,
`c14_12` INTEGER(11)  DEFAULT NULL ,
`c13_1` INTEGER(11)  DEFAULT NULL ,
`c13_2` INTEGER(11)  DEFAULT NULL ,
`c13_3` INTEGER(11)  DEFAULT NULL ,
`c13_4` INTEGER(11)  DEFAULT NULL ,
`c13_5` INTEGER(11)  DEFAULT NULL ,
`c13_6` INTEGER(11)  DEFAULT NULL ,
`c13_7` INTEGER(11)  DEFAULT NULL ,
`c13_8` INTEGER(11)  DEFAULT NULL ,
`c13_9` INTEGER(11)  DEFAULT NULL ,
`c13_10` INTEGER(11)  DEFAULT NULL ,
`c13_11` INTEGER(11)  DEFAULT NULL ,
`c13_12` INTEGER(11)  DEFAULT NULL ,
`c12_1` INTEGER(11)  DEFAULT NULL ,
`c12_2` INTEGER(11)  DEFAULT NULL ,
`c12_3` INTEGER(11)  DEFAULT NULL ,
`c12_4` INTEGER(11)  DEFAULT NULL ,
`c12_5` INTEGER(11)  DEFAULT NULL ,
`c12_6` INTEGER(11)  DEFAULT NULL ,
`c12_7` INTEGER(11)  DEFAULT NULL ,
`c12_8` INTEGER(11)  DEFAULT NULL ,
`c12_9` INTEGER(11)  DEFAULT NULL ,
`c12_10` INTEGER(11)  DEFAULT NULL ,
`c12_11` INTEGER(11)  DEFAULT NULL ,
`c12_12` INTEGER(11)  DEFAULT NULL ,
`c11_1` INTEGER(11)  DEFAULT NULL ,
`c11_2` INTEGER(11)  DEFAULT NULL ,
`c11_3` INTEGER(11)  DEFAULT NULL ,
`c11_4` INTEGER(11)  DEFAULT NULL ,
`c11_5` INTEGER(11)  DEFAULT NULL ,
`c11_6` INTEGER(11)  DEFAULT NULL ,
`c11_7` INTEGER(11)  DEFAULT NULL ,
`c11_8` INTEGER(11)  DEFAULT NULL ,
`c11_9` INTEGER(11)  DEFAULT NULL ,
`c11_10` INTEGER(11)  DEFAULT NULL ,
`c11_11` INTEGER(11)  DEFAULT NULL ,
`c11_12` INTEGER(11)  DEFAULT NULL ,
`c10_1` INTEGER(11)  DEFAULT NULL ,
`c10_2` INTEGER(11)  DEFAULT NULL ,
`c10_3` INTEGER(11)  DEFAULT NULL ,
`c10_4` INTEGER(11)  DEFAULT NULL ,
`c10_5` INTEGER(11)  DEFAULT NULL ,
`c10_6` INTEGER(11)  DEFAULT NULL ,
`c10_7` INTEGER(11)  DEFAULT NULL ,
`c10_8` INTEGER(11)  DEFAULT NULL ,
`c10_9` INTEGER(11)  DEFAULT NULL ,
`c10_10` INTEGER(11)  DEFAULT NULL ,
`c10_11` INTEGER(11)  DEFAULT NULL ,
`c10_12` INTEGER(11)  DEFAULT NULL ,
`c9_1` INTEGER(11)  DEFAULT NULL ,
`c9_2` INTEGER(11)  DEFAULT NULL ,
`c9_3` INTEGER(11)  DEFAULT NULL ,
`c9_4` INTEGER(11)  DEFAULT NULL ,
`c9_5` INTEGER(11)  DEFAULT NULL ,
`c9_6` INTEGER(11)  DEFAULT NULL ,
`c9_7` INTEGER(11)  DEFAULT NULL ,
`c9_8` INTEGER(11)  DEFAULT NULL ,
`c9_9` INTEGER(11)  DEFAULT NULL ,
`c9_10` INTEGER(11)  DEFAULT NULL ,
`c9_11` INTEGER(11)  DEFAULT NULL ,
`c9_12` INTEGER(11)  DEFAULT NULL ,
`c8_1` INTEGER(11)  DEFAULT NULL ,
`c8_2` INTEGER(11)  DEFAULT NULL ,
`c8_3` INTEGER(11)  DEFAULT NULL ,
`c8_4` INTEGER(11)  DEFAULT NULL ,
`c8_5` INTEGER(11)  DEFAULT NULL ,
`c8_6` INTEGER(11)  DEFAULT NULL ,
`c8_7` INTEGER(11)  DEFAULT NULL ,
`c8_8` INTEGER(11)  DEFAULT NULL ,
`c8_9` INTEGER(11)  DEFAULT NULL ,
`c8_10` INTEGER(11)  DEFAULT NULL ,
`c8_11` INTEGER(11)  DEFAULT NULL ,
`c8_12` INTEGER(11)  DEFAULT NULL ,
`c7_1` INTEGER(11)  DEFAULT NULL ,
`c7_2` INTEGER(11)  DEFAULT NULL ,
`c7_3` INTEGER(11)  DEFAULT NULL ,
`c7_4` INTEGER(11)  DEFAULT NULL ,
`c7_5` INTEGER(11)  DEFAULT NULL ,
`c7_6` INTEGER(11)  DEFAULT NULL ,
`c7_7` INTEGER(11)  DEFAULT NULL ,
`c7_8` INTEGER(11)  DEFAULT NULL ,
`c7_9` INTEGER(11)  DEFAULT NULL ,
`c7_10` INTEGER(11)  DEFAULT NULL ,
`c7_11` INTEGER(11)  DEFAULT NULL ,
`c7_12` INTEGER(11)  DEFAULT NULL ,
`c6_1` INTEGER(11)  DEFAULT NULL ,
`c6_2` INTEGER(11)  DEFAULT NULL ,
`c6_3` INTEGER(11)  DEFAULT NULL ,
`c6_4` INTEGER(11)  DEFAULT NULL ,
`c6_5` INTEGER(11)  DEFAULT NULL ,
`c6_6` INTEGER(11)  DEFAULT NULL ,
`c6_7` INTEGER(11)  DEFAULT NULL ,
`c6_8` INTEGER(11)  DEFAULT NULL ,
`c6_9` INTEGER(11)  DEFAULT NULL ,
`c6_10` INTEGER(11)  DEFAULT NULL ,
`c6_11` INTEGER(11)  DEFAULT NULL ,
`c6_12` INTEGER(11)  DEFAULT NULL ,
`c5_1` INTEGER(11)  DEFAULT NULL ,
`c5_2` INTEGER(11)  DEFAULT NULL ,
`c5_3` INTEGER(11)  DEFAULT NULL ,
`c5_4` INTEGER(11)  DEFAULT NULL ,
`c5_5` INTEGER(11)  DEFAULT NULL ,
`c5_6` INTEGER(11)  DEFAULT NULL ,
`c5_7` INTEGER(11)  DEFAULT NULL ,
`c5_8` INTEGER(11)  DEFAULT NULL ,
`c5_9` INTEGER(11)  DEFAULT NULL ,
`c5_10` INTEGER(11)  DEFAULT NULL ,
`c5_11` INTEGER(11)  DEFAULT NULL ,
`c5_12` INTEGER(11)  DEFAULT NULL ,
`c4_1` INTEGER(11)  DEFAULT NULL ,
`c4_2` INTEGER(11)  DEFAULT NULL ,
`c4_3` INTEGER(11)  DEFAULT NULL ,
`c4_4` INTEGER(11)  DEFAULT NULL ,
`c4_5` INTEGER(11)  DEFAULT NULL ,
`c4_6` INTEGER(11)  DEFAULT NULL ,
`c4_7` INTEGER(11)  DEFAULT NULL ,
`c4_8` INTEGER(11)  DEFAULT NULL ,
`c4_9` INTEGER(11)  DEFAULT NULL ,
`c4_10` INTEGER(11)  DEFAULT NULL ,
`c4_11` INTEGER(11)  DEFAULT NULL ,
`c4_12` INTEGER(11)  DEFAULT NULL ,
`c3_1` INTEGER(11)  DEFAULT NULL ,
`c3_2` INTEGER(11)  DEFAULT NULL ,
`c3_3` INTEGER(11)  DEFAULT NULL ,
`c3_4` INTEGER(11)  DEFAULT NULL ,
`c3_5` INTEGER(11)  DEFAULT NULL ,
`c3_6` INTEGER(11)  DEFAULT NULL ,
`c3_7` INTEGER(11)  DEFAULT NULL ,
`c3_8` INTEGER(11)  DEFAULT NULL ,
`c3_9` INTEGER(11)  DEFAULT NULL ,
`c3_10` INTEGER(11)  DEFAULT NULL ,
`c3_11` INTEGER(11)  DEFAULT NULL ,
`c3_12` INTEGER(11)  DEFAULT NULL ,
`c2_1` INTEGER(11)  DEFAULT NULL ,
`c2_2` INTEGER(11)  DEFAULT NULL ,
`c2_3` INTEGER(11)  DEFAULT NULL ,
`c2_4` INTEGER(11)  DEFAULT NULL ,
`c2_5` INTEGER(11)  DEFAULT NULL ,
`c2_6` INTEGER(11)  DEFAULT NULL ,
`c2_7` INTEGER(11)  DEFAULT NULL ,
`c2_8` INTEGER(11)  DEFAULT NULL ,
`c2_9` INTEGER(11)  DEFAULT NULL ,
`c2_10` INTEGER(11)  DEFAULT NULL ,
`c2_11` INTEGER(11)  DEFAULT NULL ,
`c2_12` INTEGER(11)  DEFAULT NULL ,
`c1_1` INTEGER(11)  DEFAULT NULL ,
`c1_2` INTEGER(11)  DEFAULT NULL ,
`c1_3` INTEGER(11)  DEFAULT NULL ,
`c1_4` INTEGER(11)  DEFAULT NULL ,
`c1_5` INTEGER(11)  DEFAULT NULL ,
`c1_6` INTEGER(11)  DEFAULT NULL ,
`c1_7` INTEGER(11)  DEFAULT NULL ,
`c1_8` INTEGER(11)  DEFAULT NULL ,
`c1_9` INTEGER(11)  DEFAULT NULL ,
`c1_10` INTEGER(11)  DEFAULT NULL ,
`c1_11` INTEGER(11)  DEFAULT NULL ,
`c1_12` INTEGER(11)  DEFAULT NULL ,
PRIMARY KEY (`id`)
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

-- 新增字段
ALTER TABLE `ppsg_checkpoint` ADD COLUMN id BIGINT(20)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN name VARCHAR(32)  DEFAULT NULL  COMMENT '名称';
ALTER TABLE `ppsg_checkpoint` ADD COLUMN forces INTEGER(11)  DEFAULT NULL  COMMENT '武力';
ALTER TABLE `ppsg_checkpoint` ADD COLUMN intellect INTEGER(11)  DEFAULT NULL  COMMENT '智力';
ALTER TABLE `ppsg_checkpoint` ADD COLUMN troops INTEGER(11)  DEFAULT NULL  COMMENT '兵力';
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c30_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c29_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c28_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c27_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c26_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c25_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c24_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c23_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c22_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c21_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c20_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c19_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c18_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c17_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c16_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c15_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c14_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c13_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c12_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c11_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c10_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c9_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c8_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c7_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c6_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c5_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c4_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c3_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c2_12 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_1 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_2 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_3 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_4 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_5 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_6 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_7 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_8 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_9 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_10 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_11 INTEGER(11)  DEFAULT NULL ;
ALTER TABLE `ppsg_checkpoint` ADD COLUMN c1_12 INTEGER(11)  DEFAULT NULL ;

